### ISSUE TITLE
Improvements needed for helm chart

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence#2123]
From @sagikazarmark 
```
- Schema migration tools should work based on a desired state:
    - Database create shouldn't fail if one exists (or should have an option not to)
    - Database schema setup shouldn't fail if it's already done (or should have an option not to)
    - Database schema update shouldn't fail if it's already done (or should have an option not to)
- Schema migration tool should have a "wait" command to wait for the desired state on the Cadence server side
    - Keyspace/database is set up
    - Schema migration is at the desired version
    Related log:
    2019/06/26 15:37:55 Incompatible versionsversion mismatch for keyspace/database: "cadence". Expected version: 0.17 cannot be greater than Actual version: 0.11
- Maybe a single schema migration command being able to:
    - Create database/keyspace when asked to
    - Init schema when asked to
    - Update schema
- Use an Alpine image without unnecessary components
    - If the schema tools support waiting cqlsh, python, mysql-client, etc are not necessary
    - We experienced DNS issues with the debian jessie image on Kubernetes, Alpine worked fine
    - See https://github.com/banzaicloud/docker-cadence and https://hub.docker.com/r/banzaicloud/cadence-server
    - Other Docker image improvements: use /usr/local/bin and /etc/cadence, do not install debug tools
- Try to disable cgo if possible
- Schema dir should not be determined based on the current directory. (CADENCE_HOME?, --root instead)
    Related log:
    2019/06/26 15:20:00 Incompatible versionsunable to read expected schema version: open /schema/cassandra/cadence/versioned: no such file or directory
- Check tool in Cadence CLI to determine readiness status (currently it's determined if Cadence listens on a tcp port)
- Accept configuration (eg. secrets) from environment variable
```

**Comment by sagikazarmark** [comment]
Here is a checklist version:

- [ ] Schema migration tools should work based on a desired state:
    - Database create shouldn't fail if one exists (or should have an option not to)
    - Database schema setup shouldn't fail if it's already done (or should have an option not to)
    - Database schema update shouldn't fail if it's already done (or should have an option not to)
- [ ] Schema migration tool should have a "wait" command to wait for the desired state on the Cadence server side
    - Keyspace/database is set up
    - Schema migration is at the desired version
- [ ] Maybe a single schema migration command being able to:
    - Create database/keyspace when asked to
    - Init schema when asked to
    - Update schema
- [x] Use an Alpine image without unnecessary components (#2325)
    - If the schema tools support waiting cqlsh, python, mysql-client, etc are not necessary
    - We experienced DNS issues with the debian jessie image on Kubernetes, Alpine worked fine
    - See https://github.com/banzaicloud/docker-cadence and https://hub.docker.com/r/banzaicloud/cadence-server
    - Other Docker image improvements: use /usr/local/bin and /etc/cadence, do not install debug tools
- [x] Try to disable cgo if possible (#2325)
- [ ] Schema dir should not be determined based on the current directory. (CADENCE_HOME?, --root instead)
- [ ] Check tool in Cadence CLI to determine readiness status (currently it's determined if Cadence listens on a tcp port)
- [x] Accept configuration (eg. secrets) from environment variable (#2325)

**Comment by ibarrajo** [comment]
Hi! we are pleased to announce that we recently released official Cadence Helm charts.

Here's the [announcement](https://cadenceworkflow.io/blog/2024/10/01/announcing-cadence-helm-charts-v0/) and [cadence-charts repo](https://github.com/uber/cadence-charts):
